// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250102124006_AddSeedingDataDiaryEntries")]
    partial class AddSeedingDataDiaryEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Watched Snow white and the axe man",
                            Created = new DateTime(2025, 1, 2, 15, 40, 5, 151, DateTimeKind.Local).AddTicks(6760),
                            Title = "Watched a movie"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Did an 8km walk",
                            Created = new DateTime(2025, 1, 2, 15, 40, 5, 151, DateTimeKind.Local).AddTicks(7162),
                            Title = "Went for a walk"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Visited Hillary to discuss his bricked phone",
                            Created = new DateTime(2025, 1, 2, 15, 40, 5, 151, DateTimeKind.Local).AddTicks(7164),
                            Title = "Visited Hillary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
